### ISSUE TITLE
ESC errors with class invariant

### ISSUE THREAD

**Issue by ducmle** [OpenJML/OpenJML#581]
Dear David, 

As promised in #580, here is a first issue that I have come across with regards to using ESC to check a class named StudentSimple. This class consists of a single field (id), a getter for this field, and a class invariant concerning the minimum id value. As you will see, this class only uses an integer type and nothingelse.

The example I wish to use is of course a more detailed Student class, but I got an error when running the ESC on it. After spending some debugging, I was able to reduce this class to the simple version above.

The command to run and the error are below. Class StudentSimple is also attached. 
The 2nd error message appears to suggest that the class invariant (line 11) is the cause of the problem. If I remove this invariant and run the ESC then it works fine.

Thanks,
Duc.

> bin/openjml esc courseman/StudentSimple.java

```
examples/src/courseman/StudentSimple.java:5: warning: The prover cannot establish an assertion (InvariantExit: examples/src/courseman/StudentSimple.java:11: ) in method StudentSimple
public class StudentSimple { 
       ^
examples/src/courseman/StudentSimple.java:11: warning: Associated declaration: examples/src/courseman/StudentSimple.java:5: 
    @  public invariant id >= 1; 
              ^
```

[StudentSimple.java.txt](https://github.com/OpenJML/OpenJML/files/1385528/StudentSimple.java.txt)

**Comment by davidcok** [comment]
Duc - 

The problem in this case is that the constructor is the default constructor, which initializes the id field to 0, and so the invariant does not hold btw the end of the constructor.

Because there is no text for the constructor, the error message points to the class name, so the problem is obscured a bit. If you use the -progress option it will be clearer that the problem is with the constructor.

Questions welcome.

- David

**Comment by ducmle** [comment]
Dear David, 

Thanks for your reply. You are right about the constructor. I added a constructor with suitable pre- and post-conditions and the class invariant is validated ok.

Duc.
