### ISSUE TITLE
RAC and java.lang.NoClassDefFoundError: org/jmlspecs/utils/Utils

### ISSUE THREAD

**Issue by vmvasconcelos** [OpenJML/OpenJML#583]
I am running an out-of-the-box Eclipse with the Open JML plugin on a mac:

$ uname -a
Darwin Arcanine.lan 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

* Installed a brand new Eclipse IDE for Java Developers, Oxygen. 1a Release (4.7.1a)
* Then the plugin, 0.8.24.
* Created a Java Project and an ArrayStack class (what else?)
* Pressed the Save key; the output in the JML Console is below and is not reassuring
* Pressed the RAC button; output as above
* Pressed the Run button; got a "Exception in thread "main" java.lang.NoClassDefFoundError: org/jmlspecs/utils/Utils"

Where are the org/jmlspecs/utils? Am I supposed to manually add them? Perhaps the class path?

Best regards,
vasco vasconcelos

------
**On save and RAC:**
Failure finding internal specs: java.net.URISyntaxException: Illegal character in path at index 26: file:/Applications/Eclipse openjml.app/Contents/Eclipse/configuration/org.eclipse.osgi/504/0/.cp/
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Failure finding internal specs: java.net.URISyntaxException: Illegal character in path at index 26: file:/Applications/Eclipse openjml.app/Contents/Eclipse/configuration/org.eclipse.osgi/504/0/.cp/
[0.00] Executing openjml on ArrayStack1.java
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
Expected a number or 'all' as argument for -escMaxWarnings: 
Unexpected value as argument for -checkFeasibility: 
[0.43] Completed
-------
**On Run**
Exception in thread "main" java.lang.NoClassDefFoundError: org/jmlspecs/utils/Utils
	at jml.ArrayStack1.<init>(ArrayStack1.java:37)
	at jml.ArrayStack1.main(ArrayStack1.java:93)
Caused by: java.lang.ClassNotFoundException: org.jmlspecs.utils.Utils
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by davidcok** [comment]
Vasco - the one thing I note about your installation is the old version of Java - and unfortunately the internal API changes a friar bit with new builds of Java - currently we are running Java 1.8.0_131 or _`141. 

As part of solving this, please also try the example on the command-line.

- David

**Comment by vmvasconcelos** [comment]
Hi David,

Got the exact same behaviour with 1.8.0_152-b16 (unfortunately could not find the 141 release at Oracle; will keep trying), *both* under eclipse and on the command line. On the command line tried "-classpath .:/Users/vv/Downloads/openjml-0.8.24-20171007/jmlspecs.jar "

In the old versions of JML, the jmlrac script would set the classpath. How does one run rac bytecodes in Open JML?

vv$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
vv$ java -jar /Users/vv/Downloads/openjml-0.8.24-20171007/openjml.jar -rac jml/ArrayStack1.java 
Note: /Users/vv/Downloads/openjml-0.8.24-20171007/openjml.jar(specs18/java/util/Random.jml) uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
vv$ java -classpath .:/Users/vv/Downloads/openjml-0.8.24-20171007/jmlspecs.jar  jml/ArrayStack1
Exception in thread "main" java.lang.NoClassDefFoundError: org/jmlspecs/utils/Utils
	at jml.ArrayStack1.<init>(ArrayStack1.java:37)
	at jml.ArrayStack1.main(ArrayStack1.java:93)
Caused by: java.lang.ClassNotFoundException: org.jmlspecs.utils.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by davidcok** [comment]
When running the compiled RAC program on the command-line, you need to include jmlruntime.jar in the class path — that is where org/jmlspecs/utils/Utils is.
Within the IDE that would be set for you.

- David

**Comment by davidcok** [comment]
Vasco - 

1) I was able to reproduce the problems you describe by creating a completely fresh new installation of Eclipse.

2) some of the problems, such as errors about the value of -checkFeasibility and -escMaxWarnings are the result of having a completely clean preferences file. You can stop these errors by opening up the preferences for OpenJML, setting these options and closing it, even if later you set them back to the supposed defaults.

3) I can also reproduce the problem in the IDE with missing jmlruntime.jar . This should work out of the box of course, but the workaround is to add the the class path in the Project Properties for the project you  are running, Go to the Project Properties, Libraries tab, click on ‘External jar’ and navigate to an instance of jmlruntime.jar from your command-line download.

At least those workarounds work for me.  My apologies it took a few days for me to sort this one out. Apologies also because ESC is taking up nearly all my time of late, so apparently RAC , especially in the IDE, as suffered. 

Let me know if this keeps you working; I’ll make a new version sometime in the near future — if you actually need a new version immediately let me know.  Also be sure to get in touch if I can help in any other way.

- David

**Comment by davidcok** [comment]
Vasco - I realized (in the night) that the mechanism to add the library into the class path is already in the OpenJMLIDE: Simply select the project and then the menu item ‘Enable JML’.  Then the internal copy of the jmlruntime library will be automatically added to the class path of of the project and the compiled class. It is well to keep in mind this dependency however, since it explains what is happening if the error message arises. I’ll add a dialog that explains this for new users.

- David

**Comment by vmvasconcelos** [comment]
Hi David,
I had figured out myself the workaround, once I realised that org/jmlspecs/utils/Utils was not in jmlspecs.jar, but in jmlruntime.jar. Never thought of the ‘Enable JML’ option; a much better solution. Thanks.
