### ISSUE TITLE
How to use OpenJML command line tool

### ISSUE THREAD

**Issue by jinjideqiangwei** [OpenJML/OpenJML#620]
My os is macOS sierra v10.12.6, and I download openjml comand line tool from http://www.openjml.org/downloads/ by click the green download link button. 

My current folder is openjml and I run the instruction below successfully.

```
java -jar openjml.jar -help
```

Then I put a source file named Main.java into the current folder. The file is 

```
public class Main {

    //@ requires a > 0;
    //@ requires b > 0;
    //@ ensures \result == a+b;
    public int add(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println("OpenJML");
    }
}
```

And I run the instruction below

```
java -jar openjml.jar -g Main.java
```

But it show me nothing. How can I know does the code pass the verification?

My java version is 1.8 and I'm new to OpenJML, I don't know how to solve this problem so help

**Comment by 912172702** [comment]
java -jar "/Users/caohui/Downloads/openjml-0.8.35-20180614/openjml.jar" -esc -prover z3_4_3 -exec /Users/caohui/Downloads/openjml-0.8.35-20180614/Solvers-macos/z3-4.3.1 -noPurityCheck ./Main.java

**Comment by davidcok** [comment]
I apologize for the delay in responding to this, as it is a simple query. If you check the instructions for running openjml (e.g. http://www.openjml.org/documentation/execution.shtml), you will see that the command you ran just does type-checking. Since there are no type errors, no error messages were printed.

If you want to do static checking or runtime checking you need to use the -esc or -rac options. See the webpage indicated above for simple examples.
