### ISSUE TITLE
What does the warning "PossiblyBadArrayAssignment" mean and how to fix the warning?

### ISSUE THREAD

**Issue by jinjideqiangwei** [OpenJML/OpenJML#628]
I'm very grateful to davidcok for the solution of the Issues [#627](https://github.com/OpenJML/OpenJML/issues/627). That works but I get another problem when I add a constructor for the class Address:

```
public class MyObjectArray {

    public class Address {
        public int address;

        //@ ensures this.address == address;
        public Address(int address) {
            this.address = address;
        }
    }

    //@ public invariant addresses.length == 100;
    public Address[] addresses = new Address[100];


    //@ ensures (\forall int i; i >= 0 && i < 100; addresses[i] != null);
    public MyObjectArray() {
        //@ maintaining i >= 0 && i <= 100;
        //@ decreasing 100 - i;
        //@ maintaining (\forall int j; j >=0 && j < i; addresses[j] != null);
        for (int i = 0; i < 100; ++i) {
            addresses[i] = new Address(88);
        }

        //@ maintaining i >= 0 && i <= 100;
        //@ decreasing 100 - i;
        //@ maintaining (\forall int j; j >=0 && j < i; addresses[j].address == 99);
        for (int i = 0; i < 100; ++i) {
            addresses[i].address = 99;
        }
    }
}
```

I got two warnings:

```
./src/main/java/main/MyObjectArray.java:24: warning: The prover cannot establish an assertion (PossiblyBadArrayAssignment) in method MyObjectArray
            addresses[i] = new Address(88);
                         ^
./src/main/java/main/MyObjectArray.java:22: warning: The prover cannot establish an assertion (LoopInvariant) in method MyObjectArray
        //@ maintaining (\forall int j; j >=0 && j < i; addresses[j] != null);
            ^
```
I don't know what the meaning of the warning "PossiblyBadArrayAssignment". And How can I elimimate this? (And the next warning seems to be caused by this warning?)

**Comment by davidcok** [comment]
First, PossiblyBadArrayAssignment.

The Java compiler allows this sort of code:
Object[] o = new String[10];
o[0] = new Integer(9);

But at runtime this will result in an ArrayStoreException because an Integer is being put into a String[] array.
So for any array assignment, like addresses[I] = new Address(), OPenJML needs to prove that the dynamic type of the rhs is a subclass of the element type of the dynamic type of the lhs.

So why is that not the case in your code and why was it OK when you used the default constructor?

The answer is that when the constructor new Address(88) is called, OpenJML looks at the specification of that constructor to see what side-effects it might have, in particular at the assignable clause.
But there is no assignable clause — so the default assignable clause is used, which allows new Address() to have any side-effects whatsoever (assignable \everything).
Thus when new Address(88) is called, anything might change, including the value of addresses — so it might no longer have the right dynamic type to be assigned to.

The fix is easy: just add //@ pure to the constructor specification. This indicates that the constructor changes nothing except the fields of the object being constructed.

>         //@ ensures this.address == address;
                    //@ pure
>         public Address(int address) {
>             this.address = address;
>         }
The default constructor did not have this problem because it had an autogenerated spec, which was automatically pure.

Also, if you do this initialization in a method rather than in a constructor (MyObjectArray()) then you will need a precondition

    //@ requires \type(Address) <: \elemtype(\typeof(addresses));

This states that ‘address’ still has the right dynamic type (nothing has changed it since it was initialized, before calling the method)

- David

**Comment by jinjideqiangwei** [comment]
Thanks a lot!
