### ISSUE TITLE
Misplaced contract causes no error

### ISSUE THREAD

**Issue by RustanLeino** [OpenJML/OpenJML#639]
An `ensures` clause placed in the middle of a method is parsed and type checked by OpenJML, but is then silently ignored. A preferred behavior would be to emit an error message saying the `ensures` clause is misplaced.

Repro:

```
public class A {
    public static void main(String[] args) {
        int x = 3;
        //@ ensures false;  // bogus to have an ensures clause here
        int y = 4;
    }
}
```

Running OpenJML on this class produces no warnings.

  Rustan

**Comment by davidcok** [comment]
JML allows statement contracts within the body of a method. The contract (which looks like a method contract) applies to the next statement, which is usually a block. The point is to be able to break the proof of a method up into sections, to make the proofs of long methods feasible.

Hence this is legal syntax. The problem is that the capability is not yet fully implemented. So a warning about the lack of checking should be issued.

**Comment by davidcok** [comment]
Closing old issue: A 'refining' statemente is required to indicate the user intent as in

public class A {
    public static void main(String[] args) {
        int x = 3;
        //@ refining
        //@   ensures false;  // bogus to have an ensures clause here
        int y = 4;
    }
}
