### ISSUE TITLE
Incorrect integer overflow warning

### ISSUE THREAD

**Issue by postmasters** [OpenJML/OpenJML#667]
```
$ java -jar openjml.jar -esc -exec Solvers-linux/z3-4.3.1 -progress A.java; echo $?
Proving methods in A
Starting proof of A.A() with prover z3_4_3
A.A Method assertions are validated
A.java:1: Feasibility check #1 - end of preconditions : OK
A.java:1: Feasibility check #2 - at program exit : OK
Completed proof of A.A() with prover z3_4_3 - no warnings [0.16 secs]
Starting proof of A.add(int) with prover z3_4_3
A.add Method assertions are INVALID
A.java:5: warning: The prover cannot establish an assertion (ArithmeticOperationRange) in method add:  overflow in int sum
    return a + 1;
             ^
Completed proof of A.add(int) with prover z3_4_3 - with warnings [0.06 secs]
Completed proving methods in A [0.24 secs]
Note: Summary:
    Valid:      1
    Invalid:    1
    Infeasible: 0
    Timeout:    0
    Error:      0
    Skipped:    0
   TOTAL:       2
   DURATION:          0.3 secs
1 warning
0
```
```
$ cat A.java
public final class A {
  // @ requires a >= 0 && a <= 10;
  // @ ensures \result == a + 1;
  public int add(int a) {
    return a + 1;
  }
}
```

I'm just trying out OpenJML for the first time with the included Z3 4.3.1 binary so this might also be my lack of knowledge to guide the checker.

**Comment by postmasters** [comment]
Changing `return a + 1` to `return ++a` validates the code, even if `&& a <= 10` is removed.

**Comment by davidcok** [comment]
Hi - thanks for trying out OpenJML

1) The version without pre and postconditions and return a+1, gives a warning about overflow. This is a correct warning. If a is Integer.MAX_VALUE, then a+1 will overflow.

2) The version with the preconditions (and fixing ensures clause to have == instead of =) validates successfully. This is also correct. Because the range of a is limited, no overflow can occur, and the 32-bit computation in Java gives the same result as the unbounded precision computation in the specification.

3) The version without preconditions and with return ++a; does not issue a warning. This is incorrect. The same warning as in (1) should be produced. Indeed I see that a refactoring of the arithmetic translation for binary operators was not applied also to ++ and —. Thanks for the bug report.

- David

**Comment by davidcok** [comment]
Corrected some time ago. Example is in test suite. Closing the issue.
