### ISSUE TITLE
Super type problem

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [OpenJML/OpenJML#687]
The attached cod can be compile by javac, but by using esc it shows unreachable problem. Also, if we do not use super type class, esc will satisfy it. 
[AgeBug.zip](https://github.com/OpenJML/OpenJML/files/3347255/AgeBug.zip)

**Comment by davidcok** [comment]
Sorry to take too long to respond to this.

1) You have given the model fields in Date a specific value. Consequently this.year always equals birth.year and the first alternative in today_later() is infeasible. If you remove the initialization of the model fields the infeasibility warning goes away. If you want to say that all constructors initialize the model fields to specific values, use a initially clause.

2) With that correction in place, the AgeBug.equals method does not verify. That is because you are missing parentheses in the postcondition of Date.equals.  Check the precedence rules.

3) In addition, you probably want the invariants to be in Date, not in AgeBug
