### ISSUE TITLE
Problem with Enable JML on the project - error code 4

### ISSUE THREAD

**Issue by DacianGoina** [OpenJML/OpenJML#708]
Hello!

I tried to use JML but I have some problems!
Before of this I want to mentioned: I use Windows 10 and Eclipse IDE (Eclipse IDE for Java developers 2020-09), and I have java 8 installed.

How I installed JML: from Eclipse->Help->Install New Software and I used [this link](http://jmlspecs.sourceforge.net/openjml-updatesite/).
When I go to top menu, JML -> Enabel JML on the the project, I receive [an error](https://imgur.com/mMjLQfL) (as a alert box) and also [an error in console](https://imgur.com/JsIPedi).  (please see these images)
![img1_error](https://user-images.githubusercontent.com/73591137/97433869-d94bb080-1926-11eb-9531-b12cfeaa7612.jpg)
![img2_error](https://user-images.githubusercontent.com/73591137/97433870-da7cdd80-1926-11eb-9f73-57bea1dc22a8.jpg)
Edit: I added images internal, so you can see the images here instead of links
How can I should fix it?

**Comment by davidcok** [comment]
I suggest you try running openjml on the command-line to check whether the problem relates to your system installation.

**Comment by davidcok** [comment]
This problem typically has one of two causes.
(a) Eclipse is being run with Java 11. You need to be sure that Eclipse is launched with java 8 being the default Java. Instead of  launching by double-clicking the eclipse app, instead launch by using a script that sets to Java 8 and then executes Eclipse. Something like:
#! /bin/bash
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
export PATH=${JAVA_HOME}/bin:$PATH
/Users/davidcok/eclipse-java8/committers-2019-12/Eclipse.app/Contents/MacOS/eclipse

(b) You are using a too-recent version of Eclipse. The 2020 Eclipse downloads are built with Java11 libraries and don't work with current OpenJML. I can run successfully with the 2019-12 version of the Eclipse IDE.

Moving to a current version of Java is in progress but is a large task.
- David
