### ISSUE TITLE
assert clause won't work 

### ISSUE THREAD

**Issue by DacianGoina** [OpenJML/OpenJML#713]
Hello! 

So, I use JML to check selection correctness sort for a project. I use [this](http://aspectjml.cin.ufpe.br/) tool for JML.
First I tried with **for** loop instead of **while** but then I changed to **while**, same effect. This is the method: 

```
package figures;
public class A{
//@ requires A.length > 0;
//@ ensures (\forall int i; i>=0 && i < A.length - 1; A[i] <= A[i+1]);
public static void selectionSort(int A[]) { 
        int n = A.length; 
        // check sort propriety for partial array (left side of A - already sorted)
        //@ assert \forall int k; k >= 0 && k < i - 1; A[k] <= A[k+1]; 
        int i = 0;
        while(i<n-1) 
        { 
            int min_idx = i; 
            int j = i+1;
            while(j<n){ 
                if (A[j] < A[min_idx]) 
                    min_idx = j; 
                j++;
            }
            // check minimum value found
            //@ assert \forall int t; t >= i + 1 && t < A.length ; A[min_idx] <= A[t];
            int temp = A[min_idx]; 
            A[min_idx] = A[i]; 
            A[i] = temp; 
            i++;
        } 
    } 


}
```

The sorting works but the problem is that **assert** has no effect: if I changend comparation sign from **assert forall** the program still works (the sorting method still works). Also, if I write anything in JML instruction inside method this action has no effect (eg.:  //@ some text, not a clause ,   this work correctly, no exception, sorting still work).

**Edit: I have the same problem with loop_invariant, has no effect inside method**

This is Main class
```   package figures;
    public class Main {
    public static void main(String[] args) {
        
        int B[] = {2,22,-1,3,8,9,1,4};
        A.selectionSort(B);
        for(int i=0;i<B.length;i++)
            System.out.print(B[i]+ " ");

    }

}

**Comment by davidcok** [comment]
The assert has no effect because it is syntactically wrong -- as running OpenJML would tell you. An assert states a property that must be true at that point in the code. For loops what you need are loop_invariants -- typically one to restrict the loop counter and one to state the inductive property that is incrementally true on each iteration of the loop and then implies the post-condition.

You say "JML has no effect". I presume what you mean is that out has no effect when you compile with Java -- well it won't. JML is comments to the Java compiler. You need to use the OpenJML tool. See openjml.org. If you are still having trouble after you have sorted all this out, get back to me again.
