### ISSUE TITLE
Error when using \old in constructor postcondition

### ISSUE THREAD

**Issue by Sophietje** [OpenJML/OpenJML#733]
I've been trying to verify the following program:
```
public class Counter {
  int value;

  //@ ensures this.value == v;
  Counter(int v)
  {
    this.value=v;
  }
  
  //@ ensures v.value == \old(v.value) && this.value == \old(v.value);
  Counter(Counter v)
  {
    this.value=v.value;
  }

  public static void main(String[] args)
  {
    Counter c1 = new Counter(3);
    Counter c2= new Counter(c1);
    //@ assert c1.value == c2.value;
  }
}
```
When trying to verify this program, OpenJML will report several errors mentioning that `Non-static fields are not allowed in \old environments in postconditions`.

Why is using a non-static variable in \old problematic? I would expect it to be reasonable in this case but I might be missing something

**Comment by davidcok** [comment]
Sophie - you are correct; this program should be allowed. The case in which ‘value’ is an instance field of a formal parameter rather than of ’this’ was missed. I will fix this. In the meantime you can specify the constructor in the following (better) way:

  //@ ensures this != v && this.value == v.value;
  //@ pure
  Counter(Counter v)
  {
    this.value=v.value;
  }

**Comment by Sophietje** [comment]
Thanks David, I'll work around it like you suggested for now

**Comment by davidcok** [comment]
The fix is on the current development branch and will be in the next release.
