### ISSUE TITLE
Incorrect proof using model variable on interface

### ISSUE THREAD

**Issue by Elewyth** [OpenJML/OpenJML#754]
Hello, I am experiencing a very weird behavior, where OpenJML thinks my code is valid, even though it clearly violates the JML annotations. I have tried to boil it down to the simplest possible example:

Interface:
```java
interface Counter {
    //@ public model instance int counter;

    /*@ requires counter < Integer.MAX_VALUE;
      @ ensures counter == 5;
     */
    void increment();
}
```
Implementation:
```java
class CounterImpl implements Counter {
    private int internalCounter = 0;

    //@ private represents counter = internalCounter;

    @Override
    public void increment() {
        internalCounter++;
    }
}
```

When I run `java -jar openjml.jar -esc -sourcepath src/main/java -verboseness 2 src/main/java/CounterImpl.java` OpenJML finishes successfuly with 2 valid methods on `CounterImpl` (default constructor and `increment()`). It should be obvious that the nonsense `ensures counter == 5;` is not fulfilled by the correct implementation of `CounterImpl`. Am I missing something in how I am using the model variable, or is this indeed a bug in OpenJML?

I am using openjml for Java 8 (there is no Windows build available yet for the 16 version, and I am too lazy to build it myself lol).

Thanks in advance!

**Comment by davidcok** [comment]
Thank you for this bug report. It is fixed in recent release V0.16.0-alpha-7 and I've back ported the fix to release V0.8.58 in the no longer current Java 8 line. 

Some explanation
1) There is a missing bit of specification. Because the value of counter depends on internalCounter, internalCounter needs to be specified as 'in' counter:  private int internalCounter = 0; //@ in counter;

2) But it should not silently fail. Indeed an error reporting this omission was already implemented in the Java16 development branch. That warning is now also back ported to the Java8 branch.

3) Even with that correction there was a bug with the ++ operator (this example worked fine with += or just assignment). That omission has been fixed.
