### ISSUE TITLE
Question about ensuring class fields in constructors and other questions.

### ISSUE THREAD

**Issue by Blomex** [OpenJML/OpenJML#759]
Hello, I'm 5th year student of University of Warsaw and I'm currently writing master thesis about static analysis of object-oriented programs, which is why I took interest in this tool.
Unfortunately I haven't found mail contact and I'm not sure the only mailing list I found is appriopriate, which is why I'm writing here.

1. How can I ensure that in constructor Postcondition are what I want them to be? There's no `\result`, since constructor returns void. Is there any way I can refer to fields of class in `ensure` statement?
example:

`Example(int y){`
 `;   this.x = y;`
 `}`
 How can I refer to field `x` of class, or ensure it is equal to `y`?

2. When I tried calling one of my annotated methods in annotation, I noticed that `old` is not implemented for static checking. My usage is as follows: 
`old int a = foo(x);`
`old int b = foo(y);`
`old int c = a + b;`
`ensures c == \result`
Is there any way around this with it, so I will be able to call method with such annotations in annotations?

3. I couldn't quite grasp what is the difference between `ghost` and `model`. While in the old version of manual I found information that `model` has value determined by `represents` clause, and `ghost` has value directly determined by its initialization, I don't quite get it. could you provide some simple examples of `model` and `ghost` statements, and which should be used when?

4. I see this tool is still under development. Perhaps I could help or contribute in some way?

**Comment by davidcok** [comment]
1) Just use the name of the field:
```
//@ ensures x == y;  // Or this.x == y if you like
Example(int y){
  this.x = y;
}
```

2) old is implemented, but I can't tell what trouble you are having without a full working example (and knowing what environment and version you are using)

3) A ghost field is used just like any other field, just that it is declared within a JML annotation. It can be initialized, assigned to in a set statement, used in other JML annotations. A model field does not have memory allocated for it -- it represents some property of an object, through the represents clause. When I get that far with the tutorial, I'll point you to examples.

4) Comments on what documentation needs more clarity is one way to start.

**Comment by Blomex** [comment]
I'm using OpenJML 0.16.0-alpha-8. 
Java version I'm using is OpenJDK 17.0.1.
Operating system is Linux 5.4.0-90-generic.
I will add the code as attachment. 
It consists of 2 classes, `Fraction2` and `GCD`
`GCD` is used to calculate greatest common denominator, and `Fraction2` is used to represent fraction as numerator and denominator, with the rules such as gcd of numerator and denominator is 1, minus sign being in the numerator, 0 having representation 0/1 and so on.

What I would like to use is to simply write `GCD.gcd(numerator, denominator) == 1` in class invariant (instead of copy pasting the clause, which says there is no common denominator). However, because `GCD.gcd()` method is using `old` statements, I'm getting note such as `Note: Not implemented for static checking: method axioms with old or forall clauses: method gcd(int,int)`

Another problem I'm facing is when for example trying to prove that `Inverse()` returns correct values. For example `      @ ensures \result.numerator == -numerator;` can't be proven without `assume` statement. I think that's because prover sees that constructor can modify `numerator`, but doesn't take in account that it actually won't do that (since gcd is already 1). Which is another reason why I would like to use `GCD.gcd()` in the annotations.
[Fraction2_and_GCD.zip](https://github.com/OpenJML/OpenJML/files/7799676/Fraction2_and_GCD.zip)

**Comment by davidcok** [comment]
Hi - sorry for the delay in replying. I have not yet had a chance to work with your code live, but I can make a few comments that should move you  forward.

- You are correct that using old in methods that are being used within specifications is not fully supported. However I think (I’ll have to check) that proofs should still be able to go through in most cases. A workaround might be to have gcd only operate on positive numbers and do any abs operations in Fraction2

- You have used ghost fields of the class Fraction2 to hold some computed values. That is fine. However, any particular method does not know whether or not those initialized values have changed. To state that you either need additional invariants . Furthermore they are initialized before the constructor runs; you would need to set them at the end of the constructor, after this.numerator and this.denominator are set.

- Numerator and denominator could also be declared final, avoiding a need for postconditions that say they do not change.

- The signals clauses are unnecessary because the methods are pure

- The "Another problem I'm facing” is primarily because you have not stated what the result of the constructor is. You need a postcondition ensures this.numerator == … && this.denominator == …

- The postcondition in Multiply and Add and Inverse (about type) is unnecessary.

- Inverse should not need to repeat as preconditions what is already stated as an invariant

- You are reasoning about division and mod — proofs of these can take a long time, especially feasibility checks (use a -timeout just in case)

- You can write a <= x <= b instead of a <= x && x <= b

- However, ultimately I think your formulation of gcd will be hard to use. For example, it is difficult (for the Z3 solver) to prove gcd(n.n) == n

David

**Comment by Blomex** [comment]
> Furthermore they are initialized before the constructor runs; you would need to set them at the end of the constructor, after this.numerator and this.denominator are set.

This is exact thing I've struggled with and is the reason why I didn't make fields numerator and denominator final. How can I initialize `ghost` variables after constructor is ran? Is it as simple as making `//@ set d = this.denominator` inside the constructor, after variables are assigned? (I somehow completely missed this operator previously, which is probably why I've struggled with it)

> You have used ghost fields of the class Fraction2 to hold some computed values. That is fine. However, any particular method does not know whether or not those initialized values have changed. To state that you either need additional invariants .

Can ghost variables be `final` as well? is it supported?

> A workaround might be to have gcd only operate on positive numbers and do any abs operations in Fraction2

This is something I'll definitely try to do.


> - The "Another problem I'm facing” is primarily because you have not stated what the result of the constructor is. You need a postcondition ensures this.numerator == … && this.denominator == … 

Exactly, this is the reason why I tried to use `GCD.gcd()` in the postcondition - and got scared away by the `method axioms with old not implemented`.

> You are correct that using old in methods that are being used within specifications is not fully supported. However I think (I’ll have to check) that proofs should still be able to go through in most cases.

(Assuming it's working), would postcondition for constructor look something like that: 
```
@ old int gcd = GCD.gcd(numerator, denominator);
@ ensures this.numerator == \old(numerator) / gcd;
@ ensures this.denominator == \old(denominator) / gcd;
```
?

Thanks for rest of the suggestions as well. I'll see where I end up and will let you know if I encounter any other problems or if I will have any other questions.

**Comment by davidcok** [comment]
Yes, you use set to hold assignments to ghost variables.
If you do this you will need invariants.
However, I refactored what you have to avoid those ghost variables, and the olds in gcd
You can do quite a bit of simplification of the pre and post conditions.

However, this is a difficult problem to tackle because
a) the version of Z3 that is shipped does not do well with modulo operations (updating to a more recent Z3 is on my TODO list)
b) with the representation for gcd you are using Z3 likely cannot prove lemmas like gcd(n/g,d/g) == 1 where g = gcd(n.d)
If you keep on with this problem, you might try limiting the range of the ints allowed, from MAX_VALUE to something small like 1000 to get things working.

- David
