### ISSUE TITLE
JML internal error occurred  (release  0.17.0-alpha-14)

### ISSUE THREAD

**Issue by Negar-Sabour** [OpenJML/OpenJML#778]
Hello,

I have received 'error: A catastrophic JML internal error occurred' once running:
' openjml -esc -method="xorFunction" error.java'

-  I am using openjml 0.17.0-alpha-14 on ubuntu 20.04
- Both error.java and output message could be found in [output.zip](https://github.com/OpenJML/OpenJML/files/8892222/output.zip).
- An interesting point is that no error happens once line 81 in error.java is removed. In other words, the error might directly relate to line 81.

regards,
Negar

**Comment by davidcok** [comment]
The problem in line 81 is that the parentheses are misplaced. Once that is fixed, the crash does not happen.

Of course the crash should not happen (it is triggered by the type resolution error because of the misplaced right parenthesis) -- the fix for that is still being investigated.

**Comment by davidcok** [comment]
Added a test (gitbug778) in OpenJML21 and confirmed that this problem is fixed: it does not crash and it does give a reasonable error message

**Comment by davidcok** [comment]
There was a further problem that related to having both an xor function (which forced using bit-vectors) and a cast to byte.
Without bit-vectors, integral types are all SMT 'int', so the cast can be omitted, but with bit-vectors, one must keep to cast in order to adjust the length of the bit-vector.  Fixed for the version after 21-0.6.
