### ISSUE TITLE
Issues on Dynamic Binding and RAC Verification 

### ISSUE THREAD

**Issue by marcel139** [OpenJML/OpenJML#794]
In the following example, I would expect the verification of SubExample to fail on ESC but to succeed on RAC. This is because, since `sp` is declared as a `SuperExample`, the static verification considers the pre-condition `x > 0` from that class. However, since it was instantiated with a `SubExample`, dynamically, it should consider the pre-condition of the `SubExample` class (`x > 0 || x >= 0`).

Nevertheless, this example is failing in bot, ESC and RAC. 

@davidcok Do you consider this as an issue to be fixed?

```
public class SuperExample {
    //@ spec_public 
    protected int x = 0;

    //@ ensures this.x == x;
    //@ pure
    SuperExample(int x) { this.x = x; }

    //@ ensures \result == x;
    //@ pure
    public int getX() { return x; }

    //@ requires x > 0;
    //@ assigns this.x;
    //@ ensures this.x == x;
    public void setX(int x) { this.x = x; }
}

public class SubExample extends SuperExample{ 
    
    //@ pure
    SubExample(int x) { super(x); }
    
    //@ also
    //@ requires x >= 0;
    //@ assigns this.x;
    //@ ensures this.x == x;
    public void setX(int x){ this.x = x; }
    
    public static void main(String[] args) {
        SuperExample sp = new SubExample(10);
        sp.setX(0);
    }
   
}

```

**Comment by leavens** [comment]
Hi Marcel,

The RAC should be checking the same conditions as ESC is checking. That is, since sp has the static type SuperExample, the call sp.setX(0) should check the precondition from the type SuperExample. So the RAC should also note that this is a violation.  If you want to use the subtype's precondition, then you should use a different call, such as ((SubEample)sp).setX(0).

See also the paper:

  *   Henrique Rebêlo<http://www.cin.ufpe.br/~hemr/>, Gary T. Leavens<http://www.eecs.ucf.edu/~leavens/>, and Ricardo Lima<http://www.cin.ufpe.br/~rmfl>. Modular Enforcement of Supertype Abstraction and Information Hiding with Client-Side Checking. Dept. of Electrical Engineering and Computer Science, University of Central Florida, CS-TR-12-03, January 2012. [abstract]<http://www.eecs.ucf.edu/~leavens/tech-reports/UCF/CS-TR-12-03/TR.abstract.txt> [Preprint PDF]<http://www.eecs.ucf.edu/~leavens/tech-reports/UCF/CS-TR-12-03/TR.pdf>

        Regards,

        Gary T. Leavens
        329 L3Harris Center
        Computer Science, University of Central Florida
        4000 Central Florida Blvd., Orlando, FL 32816-2362 USA
        http://www.cs.ucf.edu/~leavens phone: +1-407-823-4758
        ***@***.******@***.***>

From: marcel139 ***@***.***>
Sent: Friday, March 3, 2023 10:52 AM
To: OpenJML/OpenJML ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenJML/OpenJML] Issues on Dynamic Binding and RAC Verification (Issue #794)


In the following example, I would expect the verification of SubExample to fail on ESC but to succeed on RAC. This is because, since sp is declared as a SuperExample, the static verification considers the pre-condition x > 0. However, since it was instantiated with a SubExample, dynamically, it should consider the pre-condition of the SubExample class (x > 0 || x >= 0).

@davidcok<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavidcok&data=05%7C01%7CLeavens%40ucf.edu%7Cda54e944f1e749a2d73d08db1bff3e47%7Cbb932f15ef3842ba91fcf3c59d5dd1f1%7C0%7C0%7C638134555297460587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tpmhjGikB9YYkbpl2hK7f6wLq8pxOmUSPyMiyEqRJHE%3D&reserved=0> Do you consider this as an issue to be fixed?

public class SuperExample {

    //@ spec_public

    protected int x = 0;



    //@ ensures this.x == x;

    //@ pure

    SuperExample(int x) { this.x = x; }



    //@ ensures \result == x;

    //@ pure

    public int getX() { return x; }



    //@ requires x > 0;

    //@ assigns this.x;

    //@ ensures this.x == x;

    public void setX(int x) { this.x = x; }

}



public class SubExample extends SuperExample{



    //@ pure

    SubExample(int x) { super(x); }



    //@ also

    //@ requires x >= 0;

    //@ assigns this.x;

    //@ ensures this.x == x;

    public void setX(int x){ this.x = x; }



    public static void main(String[] args) {

        SuperExample sp = new SubExample(10);

        sp.setX(0);

    }



}



-

**Comment by marcel139** [comment]
Hi Gary. Thanks for your prompt and clarifying reply.

**Comment by marcel139** [comment]
@leavens Thanks for the paper. I remember having a discussion with Henrique about this. Your the paper clearly differentiates the approaches (client-side / supplier-side) specifications. So, I see that it is correct to say that the most appropriate approach to ensure a modular verification is to use the client-side approach (as the title of the paper suggests) ;-)
